{{- if .Values.privateRegistry -}}
{{- if .Values.daemonset.useLegacy }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "okteto.fullname" . }}-dockerconfig"
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-dockerconfig"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  config.json: "{{ include "okteto.dockerconfigRoot" .Values.privateRegistry | b64enc }}"
{{- end -}}
{{- end -}}
